# https://github.com/GoogleCloudPlatform/rabbitmq-docker/blob/master/3/README.md
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-rabbitmq
  labels:
    app: {{ .Release.Name }}-rabbitmq
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: launcher.gcr.io/google/rabbitmq3:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          ports:
            - name: rabbitmq
              containerPort: 5672
              protocol: TCP
