#https://github.com/GoogleCloudPlatform/redis-docker/tree/master/4
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Release.Name }}-redis
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
    spec:
      containers:
        - name: redis
          image: launcher.gcr.io/google/redis4
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 50m
          ports:
            - name: redis
              containerPort: 6379
