apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/websocket-services: "{{ .Release.Name }}-events"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    ingress.kubernetes.io/proxy-body-size: 500m
  name: {{ .Release.Name }}-ingress
  labels:
    app: {{ .Release.Name }}
spec:
  rules:
    - host:  {{ .Values.TAIGA_HOSTNAME }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-frontend
              servicePort: 8888
          - path: /api
            backend:
              serviceName: {{ .Release.Name }}-backend
              servicePort: 8000
          - path: /events
            backend:
              serviceName: {{ .Release.Name }}-events
              servicePort: 8888

  tls:
      - hosts:
          - {{ .Values.TAIGA_HOSTNAME }}
        secretName: {{ .Values.TAIGA_HOSTNAME }}-tls


