apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Release.Name }}-frontend
spec:
  ports:
    - port: 8888
      targetPort: 8888
      name: http
  selector:
    app: {{ .Release.Name }}-frontend

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: {{ .Release.Name }}-backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rabbitmq
  labels:
    app: {{ .Release.Name }}-rabbitmq
spec:
  ports:
    - port: 5672
      targetPort: 5672
      name: rabbitmq
  selector:
    app: {{ .Release.Name }}-rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-events
  labels:
    app: {{ .Release.Name }}-events
spec:
  ports:
    - port: 8888
      targetPort: 8888
      name: http
  selector:
    app: {{ .Release.Name }}-events

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Release.Name }}-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: {{ .Release.Name }}-redis


---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    app: {{ .Release.Name }}-postgresql
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgresql
  selector:
    app: {{ .Release.Name }}-postgresql

